package adapter

import (
	"context"
	"fmt"

	"github.com/marstid/goznp/pkg/zcl"
)

// Helper functions to convert interface{} to specific types
func toUint16(v interface{}) (uint16, bool) {
	switch val := v.(type) {
	case uint16:
		return val, true
	case int16:
		return uint16(val), true
	case uint8:
		return uint16(val), true
	case int:
		return uint16(val), true
	}
	return 0, false
}

func toInt16(v interface{}) (int16, bool) {
	switch val := v.(type) {
	case int16:
		return val, true
	case uint16:
		return int16(val), true
	case int:
		return int16(val), true
	}
	return 0, false
}

func toInt8(v interface{}) (int8, bool) {
	switch val := v.(type) {
	case int8:
		return val, true
	case uint8:
		return int8(val), true
	case int:
		return int8(val), true
	}
	return 0, false
}

func toUint32(v interface{}) (uint32, bool) {
	switch val := v.(type) {
	case uint32:
		return val, true
	case int32:
		return uint32(val), true
	case uint16:
		return uint32(val), true
	case int:
		return uint32(val), true
	}
	return 0, false
}

func toInt32(v interface{}) (int32, bool) {
	switch val := v.(type) {
	case int32:
		return val, true
	case uint32:
		return int32(val), true
	case int:
		return int32(val), true
	}
	return 0, false
}

func toUint48(v interface{}) (uint64, bool) {
	switch val := v.(type) {
	case uint64:
		return val, true
	case int64:
		return uint64(val), true
	case uint32:
		return uint64(val), true
	case int:
		return uint64(val), true
	}
	return 0, false
}

// Alarms Cluster (0x0009)

// AlarmEntry represents an entry in the device's alarm log.
// Alarms can be generated by various conditions on the device (e.g., low battery, temperature threshold).
type AlarmEntry struct {
	AlarmCode uint8         // Alarm code identifying the type of alarm
	ClusterID zcl.ClusterID // Cluster that generated the alarm
	Timestamp uint32        // Time when alarm occurred (Zigbee time, seconds since 2000-01-01)
}

// GetAlarmCount reads the number of alarm entries currently stored in the device's alarm log.
// Returns the count of active alarms.
func (a *Adapter) GetAlarmCount(ctx context.Context, nwkAddr uint16, endpoint uint8) (uint16, error) {
	results, err := a.ReadAttributes(ctx, nwkAddr, endpoint, zcl.ClusterAlarms, zcl.AttrAlarmCount)
	if err != nil {
		return 0, fmt.Errorf("failed to read alarm count: %w", err)
	}

	if len(results) == 0 {
		return 0, fmt.Errorf("no attributes returned")
	}

	result := results[0]
	if result.Status != zcl.StatusSuccess {
		return 0, fmt.Errorf("read alarm count returned status 0x%02X", result.Status)
	}

	if count, ok := toUint16(result.Value); ok {
		return count, nil
	}
	return 0, fmt.Errorf("unexpected value type: %T", result.Value)
}

// ResetAlarm clears a specific alarm from the device's alarm log.
// The alarm is identified by its alarm code and the cluster that generated it.
//
// Parameters:
//   - alarmCode: The alarm code to reset (device-specific)
//   - clusterID: The cluster ID that generated the alarm
//
// Example: Reset a low battery alarm (code 0x00) from PowerConfiguration cluster:
//
//	err := adapter.ResetAlarm(ctx, nwkAddr, endpoint, 0x00, zcl.ClusterPowerConfig)
func (a *Adapter) ResetAlarm(ctx context.Context, nwkAddr uint16, endpoint uint8, alarmCode uint8, clusterID zcl.ClusterID) error {
	// ResetAlarm payload: alarmCode (1 byte) + clusterID (2 bytes LE)
	payload := []byte{
		alarmCode,
		byte(clusterID & 0xFF),
		byte(clusterID >> 8),
	}
	return a.SendClusterCommand(ctx, nwkAddr, endpoint, zcl.ClusterAlarms, zcl.CmdAlarmsResetAlarm, payload)
}

// ResetAllAlarms clears all alarms from the device's alarm log.
// This removes all active alarm entries.
func (a *Adapter) ResetAllAlarms(ctx context.Context, nwkAddr uint16, endpoint uint8) error {
	// ResetAllAlarms command has no payload
	return a.SendClusterCommand(ctx, nwkAddr, endpoint, zcl.ClusterAlarms, zcl.CmdAlarmsResetAllAlarms, nil)
}

// GetAlarm retrieves the oldest alarm entry from the device's alarm log.
// The device returns the first alarm in its log (FIFO order).
// Returns nil if there are no alarms in the log.
//
// The alarm is not removed from the log by this command; use ResetAlarm or ResetAllAlarms to clear it.
func (a *Adapter) GetAlarm(ctx context.Context, nwkAddr uint16, endpoint uint8) (*AlarmEntry, error) {
	a.mu.Lock()
	if !a.isOpen {
		a.mu.Unlock()
		return nil, ErrNotOpen
	}
	a.mu.Unlock()

	// Build and send GetAlarm request (no payload)
	seqNum := a.nextTransactionID()
	frame := zcl.BuildClusterCommand(seqNum, zcl.CmdAlarmsGetAlarm, nil)

	respFrame, err := a.sendZclRequest(ctx, nwkAddr, endpoint, uint16(zcl.ClusterAlarms), frame)
	if err != nil {
		return nil, fmt.Errorf("get alarm failed: %w", err)
	}

	// Parse GetAlarmResponse (command 0x01)
	if respFrame.CommandID != zcl.CmdAlarmsGetAlarmResponse {
		return nil, fmt.Errorf("unexpected response command: 0x%02X", respFrame.CommandID)
	}

	// GetAlarmResponse payload:
	// - status (1 byte): 0x00 = success, others = error/no alarms
	// - alarmCode (1 byte) - only if status is success
	// - clusterID (2 bytes LE) - only if status is success
	// - timestamp (4 bytes LE) - only if status is success
	if len(respFrame.Payload) < 1 {
		return nil, fmt.Errorf("response too short")
	}

	status := zcl.Status(respFrame.Payload[0])
	if status != zcl.StatusSuccess {
		// No alarms in log or error
		if status == zcl.StatusFailure { // NOT_FOUND
			return nil, nil
		}
		return nil, fmt.Errorf("get alarm returned status 0x%02X", status)
	}

	// Parse successful response
	if len(respFrame.Payload) < 8 {
		return nil, fmt.Errorf("response payload too short for alarm entry")
	}

	entry := &AlarmEntry{
		AlarmCode: respFrame.Payload[1],
		ClusterID: zcl.ClusterID(uint16(respFrame.Payload[2]) | uint16(respFrame.Payload[3])<<8),
		Timestamp: uint32(respFrame.Payload[4]) | uint32(respFrame.Payload[5])<<8 |
			uint32(respFrame.Payload[6])<<16 | uint32(respFrame.Payload[7])<<24,
	}

	return entry, nil
}

// ResetAlarmLog clears the entire alarm log on the device.
// This removes all alarm history but does not prevent new alarms from being generated.
func (a *Adapter) ResetAlarmLog(ctx context.Context, nwkAddr uint16, endpoint uint8) error {
	// ResetAlarmLog command has no payload
	return a.SendClusterCommand(ctx, nwkAddr, endpoint, zcl.ClusterAlarms, zcl.CmdAlarmsResetAlarmLog, nil)
}

// Price Cluster (0x0700) - Smart Energy Profile

// PriceInfo contains pricing information from the Price cluster.
// This is part of the Smart Energy profile used for dynamic pricing and
// demand response applications.
type PriceInfo struct {
	ProviderId         uint32 // Unique identifier for the commodity supplier
	RateLabel          string // User-defined rate label (e.g., "Peak", "Off-Peak")
	IssuerEventId      uint32 // Unique identifier for this pricing event
	CurrentTime        uint32 // Current time in Zigbee time (seconds since 2000-01-01)
	UnitOfMeasure      uint8  // Unit of measurement (kWh, m3, etc.)
	Currency           uint16 // ISO 4217 currency code (e.g., 840 = USD)
	PriceTrailingDigit uint8  // Number of digits to right of decimal point
	NumberOfTiers      uint8  // Number of price tiers in use
	Price              uint32 // Price in currency units (apply trailing digit)
	StartTime          uint32 // When this price becomes effective (Zigbee time)
	DurationInMinutes  uint16 // How long this price is valid
}

// GetCurrentPrice requests the current price from a smart energy device.
// This sends a GetCurrentPrice command to the device and waits for a
// PublishPrice response containing the current pricing information.
//
// The device must support the Price cluster (0x0700) for this to work.
// This is commonly used with smart meters and energy management systems.
//
// Returns PriceInfo with pricing details, or an error if the request fails.
func (a *Adapter) GetCurrentPrice(ctx context.Context, nwkAddr uint16, endpoint uint8) (*PriceInfo, error) {
	a.mu.Lock()
	if !a.isOpen {
		a.mu.Unlock()
		return nil, ErrNotOpen
	}
	a.mu.Unlock()

	// Build GetCurrentPrice command (command ID 0x00, no payload for basic request)
	// The full command payload can include CommandOptions (1 byte), but for a simple
	// request for current price, we use an empty payload or 0x00 for default options.
	seqNum := a.nextTransactionID()
	payload := []byte{0x00} // CommandOptions: 0x00 = RequestorRxOnWhenIdle
	frame := zcl.BuildClusterCommand(seqNum, zcl.CmdPriceGetCurrentPrice, payload)

	respFrame, err := a.sendZclRequest(ctx, nwkAddr, endpoint, uint16(zcl.ClusterPrice), frame)
	if err != nil {
		return nil, fmt.Errorf("get current price failed: %w", err)
	}

	// Parse PublishPrice response (command 0x00 from server)
	if respFrame.CommandID != zcl.CmdPricePublishPrice {
		return nil, fmt.Errorf("unexpected response command: 0x%02X (expected PublishPrice 0x00)", respFrame.CommandID)
	}

	// Parse PublishPrice payload
	// Format (minimum): providerId (4) + rateLabel (var) + issuerEventId (4) + currentTime (4) +
	//                   unitOfMeasure (1) + currency (2) + priceTrailingDigit (1) +
	//                   numberOfPriceTiers (1) + registerTier (1) + startTime (4) +
	//                   durationInMinutes (2) + price (4) + ...
	if len(respFrame.Payload) < 28 {
		return nil, fmt.Errorf("publish price response too short: %d bytes", len(respFrame.Payload))
	}

	info := &PriceInfo{}
	offset := 0

	// ProviderId (uint32)
	info.ProviderId = uint32(respFrame.Payload[offset]) |
		uint32(respFrame.Payload[offset+1])<<8 |
		uint32(respFrame.Payload[offset+2])<<16 |
		uint32(respFrame.Payload[offset+3])<<24
	offset += 4

	// RateLabel (octet string with length prefix)
	if offset >= len(respFrame.Payload) {
		return nil, fmt.Errorf("payload truncated at rateLabel")
	}
	labelLen := int(respFrame.Payload[offset])
	offset++
	if offset+labelLen > len(respFrame.Payload) {
		return nil, fmt.Errorf("payload truncated in rateLabel")
	}
	info.RateLabel = string(respFrame.Payload[offset : offset+labelLen])
	offset += labelLen

	// IssuerEventId (uint32)
	if offset+4 > len(respFrame.Payload) {
		return nil, fmt.Errorf("payload truncated at issuerEventId")
	}
	info.IssuerEventId = uint32(respFrame.Payload[offset]) |
		uint32(respFrame.Payload[offset+1])<<8 |
		uint32(respFrame.Payload[offset+2])<<16 |
		uint32(respFrame.Payload[offset+3])<<24
	offset += 4

	// CurrentTime (uint32)
	if offset+4 > len(respFrame.Payload) {
		return nil, fmt.Errorf("payload truncated at currentTime")
	}
	info.CurrentTime = uint32(respFrame.Payload[offset]) |
		uint32(respFrame.Payload[offset+1])<<8 |
		uint32(respFrame.Payload[offset+2])<<16 |
		uint32(respFrame.Payload[offset+3])<<24
	offset += 4

	// UnitOfMeasure (uint8)
	if offset+1 > len(respFrame.Payload) {
		return nil, fmt.Errorf("payload truncated at unitOfMeasure")
	}
	info.UnitOfMeasure = respFrame.Payload[offset]
	offset++

	// Currency (uint16)
	if offset+2 > len(respFrame.Payload) {
		return nil, fmt.Errorf("payload truncated at currency")
	}
	info.Currency = uint16(respFrame.Payload[offset]) | uint16(respFrame.Payload[offset+1])<<8
	offset += 2

	// PriceTrailingDigit (upper 4 bits) and PriceTier (lower 4 bits) in one byte
	if offset+1 > len(respFrame.Payload) {
		return nil, fmt.Errorf("payload truncated at priceTrailingDigit")
	}
	priceTrailingDigitAndTier := respFrame.Payload[offset]
	info.PriceTrailingDigit = (priceTrailingDigitAndTier >> 4) & 0x0F
	offset++

	// NumberOfPriceTiersAndRegisterTier (upper 4 bits = number of tiers, lower 4 bits = register tier)
	if offset+1 > len(respFrame.Payload) {
		return nil, fmt.Errorf("payload truncated at numberOfTiers")
	}
	numberOfTiersAndRegisterTier := respFrame.Payload[offset]
	info.NumberOfTiers = (numberOfTiersAndRegisterTier >> 4) & 0x0F
	offset++

	// StartTime (uint32)
	if offset+4 > len(respFrame.Payload) {
		return nil, fmt.Errorf("payload truncated at startTime")
	}
	info.StartTime = uint32(respFrame.Payload[offset]) |
		uint32(respFrame.Payload[offset+1])<<8 |
		uint32(respFrame.Payload[offset+2])<<16 |
		uint32(respFrame.Payload[offset+3])<<24
	offset += 4

	// DurationInMinutes (uint16)
	if offset+2 > len(respFrame.Payload) {
		return nil, fmt.Errorf("payload truncated at duration")
	}
	info.DurationInMinutes = uint16(respFrame.Payload[offset]) | uint16(respFrame.Payload[offset+1])<<8
	offset += 2

	// Price (uint32)
	if offset+4 > len(respFrame.Payload) {
		return nil, fmt.Errorf("payload truncated at price")
	}
	info.Price = uint32(respFrame.Payload[offset]) |
		uint32(respFrame.Payload[offset+1])<<8 |
		uint32(respFrame.Payload[offset+2])<<16 |
		uint32(respFrame.Payload[offset+3])<<24

	return info, nil
}

// Smart Energy Messaging Cluster (0x0703)

// SEMessage represents a Smart Energy message to be displayed on a device.
// This is used with the Messaging cluster (0x0703) in the Smart Energy profile.
type SEMessage struct {
	MessageID uint32 // Unique message identifier
	Control   uint8  // MessageControl bitmap (transmission, importance, confirmation)
	StartTime uint32 // Zigbee time when message should be displayed (0 = now)
	Duration  uint16 // Duration to display message in minutes (0xFFFF = until explicitly cancelled)
	Message   string // Message text to display
}

// DisplaySEMessage sends a message to be displayed on a Smart Energy device.
// The message is sent using the Messaging cluster (0x0703) DisplayMessage command.
//
// Parameters:
//   - msg: The message to display, including message ID, control flags, timing, and text
//
// The Control field is a bitmap specifying:
//   - Transmission type (normal or anonymous)
//   - Importance level (low, medium, high, critical)
//   - Whether confirmation is required
//
// Use zcl.SEMsgCtrl* constants to build the control byte.
//
// Example: Display a high-importance message immediately for 60 minutes:
//
//	msg := adapter.SEMessage{
//	    MessageID: 1,
//	    Control:   zcl.SEMsgCtrlImportanceHigh | zcl.SEMsgCtrlConfirmationRequired,
//	    StartTime: 0, // Display now
//	    Duration:  60, // 60 minutes
//	    Message:   "High electricity demand. Please reduce usage.",
//	}
//	err := adapter.DisplaySEMessage(ctx, nwkAddr, endpoint, msg)
func (a *Adapter) DisplaySEMessage(ctx context.Context, nwkAddr uint16, endpoint uint8, msg SEMessage) error {
	// DisplayMessage payload format:
	// - messageId (4 bytes LE)
	// - messageControl (1 byte)
	// - startTime (4 bytes LE)
	// - durationInMinutes (2 bytes LE)
	// - message (string with 1-byte length prefix)

	msgBytes := []byte(msg.Message)
	if len(msgBytes) > 255 {
		msgBytes = msgBytes[:255] // Maximum message length per ZCL spec
	}

	payload := make([]byte, 12+len(msgBytes))

	// MessageID (4 bytes LE)
	payload[0] = byte(msg.MessageID & 0xFF)
	payload[1] = byte((msg.MessageID >> 8) & 0xFF)
	payload[2] = byte((msg.MessageID >> 16) & 0xFF)
	payload[3] = byte((msg.MessageID >> 24) & 0xFF)

	// MessageControl (1 byte)
	payload[4] = msg.Control

	// StartTime (4 bytes LE)
	payload[5] = byte(msg.StartTime & 0xFF)
	payload[6] = byte((msg.StartTime >> 8) & 0xFF)
	payload[7] = byte((msg.StartTime >> 16) & 0xFF)
	payload[8] = byte((msg.StartTime >> 24) & 0xFF)

	// Duration (2 bytes LE)
	payload[9] = byte(msg.Duration & 0xFF)
	payload[10] = byte(msg.Duration >> 8)

	// Message string (length + text)
	payload[11] = byte(len(msgBytes))
	copy(payload[12:], msgBytes)

	return a.SendClusterCommand(ctx, nwkAddr, endpoint, zcl.ClusterSEMessaging, zcl.CmdSEMessagingDisplayMessage, payload)
}

// CancelSEMessage cancels a specific message on a Smart Energy device.
// This sends a CancelMessage command to remove a previously displayed message.
//
// Parameters:
//   - messageID: The unique identifier of the message to cancel
//
// Example: Cancel message with ID 1:
//
//	err := adapter.CancelSEMessage(ctx, nwkAddr, endpoint, 1)
func (a *Adapter) CancelSEMessage(ctx context.Context, nwkAddr uint16, endpoint uint8, messageID uint32) error {
	// CancelMessage payload: messageId (4 bytes LE) + messageControl (1 byte)
	// We use control byte 0x00 for normal cancellation
	payload := []byte{
		byte(messageID & 0xFF),
		byte((messageID >> 8) & 0xFF),
		byte((messageID >> 16) & 0xFF),
		byte((messageID >> 24) & 0xFF),
		0x00, // messageControl (not used for cancel, set to 0)
	}

	return a.SendClusterCommand(ctx, nwkAddr, endpoint, zcl.ClusterSEMessaging, zcl.CmdSEMessagingCancelMessage, payload)
}

// GetLastSEMessage requests the last message from a Smart Energy device.
// This sends a GetLastMessage command and waits for the device to respond with
// the last message it received.
//
// Returns the last message, or nil if no message is available.
//
// Note: This is an asynchronous operation. The device will respond with a
// DisplayMessage command containing the last message. This method sends the
// request but does not wait for the response. You'll need to listen for
// incoming DisplayMessage commands to receive the message.
//
// Example:
//
//	err := adapter.GetLastSEMessage(ctx, nwkAddr, endpoint)
//	// Listen for DisplayMessage response separately
func (a *Adapter) GetLastSEMessage(ctx context.Context, nwkAddr uint16, endpoint uint8) error {
	// GetLastMessage command has no payload
	return a.SendClusterCommand(ctx, nwkAddr, endpoint, zcl.ClusterSEMessaging, zcl.CmdSEMessagingGetLastMessage, nil)
}
